### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by shadonovitch** [shadonovitch/dird-project-front#13]
We need to be able to dispatch Redux actions to populate a rendered WoofList dynamically.

**Comment by XenoDaimon** [comment]
So we chose to go on a redux / redux-saga style I guess.
I can work on implementing Redux and link everything with the WoofList

**Comment by shadonovitch** [comment]
I said redux because I know that corresponds to the problem here. I heard that React Context API should have made Redux useless, but I couldn't get it to work when I tried. If you can tackle this issue using Context i have no problems with that.

**Comment by XenoDaimon** [comment]
I'll see what I can do about that then

**Comment by shadonovitch** [comment]
We should use [redux-persist](https://github.com/rt2zz/redux-persist) to store the user's token instead of writing it directly in cookies.

**Comment by XenoDaimon** [comment]
Why not use the localStorage with a unmount/mount sync to store/retrieve such things?  
I'll take a look at redux-persist though.

**Comment by shadonovitch** [comment]
Added store, reducers, `fetchProfile(token)`, `fetchProfilePicture(token)` and `fetchUserWoofs(token)` actions in #20
